# Generated by Django 5.0.6 on 2025-05-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartments_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number_of_bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number_of_rooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='unit_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='unit_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
